language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: hhvm
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
    - composer install

script: phpunit

notifications:
  email: false
